app/views/apart_views.py
from flask import Blueprint, render_template, request
#from ..forms import ApartSearchForm
from ..models import BjdCode, AptDeal
import pandas as pd
import re

bp = Blueprint('apartment', __name__, url_prefix='/apartment')

@bp.route('/')
def input_keyword():
    return render_template('apart/apartment.html')

@bp.route('/search_code/')
def search_code():
    keyword = request.args.get("keyword")
    
    #관리용 코드
    
    if 'admindata$' in keyword:
        command = (keyword.split())[1]
        #공공데이터포털 아파트 실거래가 데이터베이스 만들기
        if command == 'makepricedb':
            p = re.compile('20[1-2][0-9][0-1][0-9]')
            yearmonth = (keyword.split())[2]
            if p.match(yearmonth):
                makepricedb(yearmonth)
                return render_template('apart/apartment_DB.html', dbcode=1)
            else: return render_template('apart/apartment.html')
        #makebjddb 공공데이터포털 아파트의 법정동코드 데이터베이스 만들기
        elif command == 'makebjddb':
            makebjddb()
            return render_template('apart/apartment_DB.html', dbcode=2)
        #법정동 코드리스트 보기
        elif command == 'showbjdlist':
            sidoList, bjdCodeList = showbjdlist()
            return render_template('apart/apartment_DB.html', dbcode=3, sidoList=sidoList, bjdCodeList=bjdCodeList)
        #아파트 이름 교정하기
        elif command == 'namecorrection':
            namecorrection()
            return render_template('apart/apartment_DB.html', dbcode=4)
        elif command == 'delpricedb':
            p = re.compile('20[1-2][0-9][0-1][0-9]')
            yearmonth = (keyword.split())[2]
            if p.match(yearmonth):
                delpricedb(yearmonth)
                return render_template('apart/apartment_DB.html', dbcode=5)
            else: return render_template('apart/apartment.html')
        else: return render_template('apart/apartment_DB.html')

    #아파트실거래가 검색하기
    else:
        if '이편한' in keyword:
            keyword = keyword.replace('이편한', '이편한세상')
        
        bjdList = checkBjdcode(keyword)
        #print(bjdList)
        if len(bjdList) == 1:
            bjdong = bjdList[0]
            aptList = checkApartname(keyword, bjdong)
            #print(aptList)
            if len(aptList) == 1:
                aptname = aptList[0]
                areaList = checkApartarea(bjdong, aptname)
                return render_template('apart/apartment_search_area.html', keyword=keyword, bjdong=bjdong, aptname=aptname, areaList=areaList)
            return render_template('apart/apartment_search_name.html', keyword=keyword, bjdong=bjdong, aptList=aptList)
        return render_template('apart/apartment_search_code.html', keyword=keyword, bjdList=bjdList)
    

    #배포용 코드
    '''
    if '이편한' in keyword:
        keyword = keyword.replace('이편한', '이편한세상')
    
    bjdList = checkBjdcode(keyword)
    #print(bjdList)
    if len(bjdList) == 1:
        bjdong = bjdList[0]
        aptList = checkApartname(keyword, bjdong)
        #print(aptList)
        if len(aptList) == 1:
            aptname = aptList[0]
            areaList = checkApartarea(bjdong, aptname)
            return render_template('apart/apartment_search_area.html', keyword=keyword, bjdong=bjdong, aptname=aptname, areaList=areaList)
        return render_template('apart/apartment_search_name.html', keyword=keyword, bjdong=bjdong, aptList=aptList)
    return render_template('apart/apartment_search_code.html', keyword=keyword, bjdList=bjdList)
    '''

@bp.route('/search_name/', methods=('GET', 'POST'))
def search_name():
    if request.method == 'POST':
        keyword = request.form["keyword"]
        bjdong = request.form["bjdong"]
        aptList = checkApartname(keyword, bjdong)
        if len(aptList) == 1:
            aptname = aptList[0]
            areaList = checkApartarea(bjdong, aptname)
            return render_template('apart/apartment_search_area.html', keyword=keyword, bjdong=bjdong, aptname=aptname, areaList=areaList)
        return render_template('apart/apartment_search_name.html', keyword=keyword, bjdong=bjdong, aptList=aptList)
    return render_template('apart/apartment.html')

@bp.route('/search_area/', methods=('GET', 'POST'))
def search_area():
    if request.method == 'POST':
        keyword = request.form["keyword"]
        bjdong = request.form["bjdong"]
        aptname = request.form["aptname"]
        areaList = checkApartarea(bjdong, aptname)
        return render_template('apart/apartment_search_area.html', keyword=keyword, bjdong=bjdong, aptname=aptname, areaList=areaList)
    return render_template('apart/apartment.html')

@bp.route('/search_result/', methods=('GET', 'POST'))
def search_result():
    if request.method == 'POST':
        keyword = request.form["keyword"]
        bjdong = request.form["bjdong"]
        aptname = request.form["aptname"]
        area = request.form["area"]
        buildyear, resultList = loadDealprice(bjdong, aptname, area)
        return render_template('apart/apartment_search_result.html', keyword=keyword, bjdong=bjdong, aptname=aptname, area=area, buildyear=buildyear, resultList=resultList)
    return render_template('apart/apartment.html')



#아파트 실거래가 불러오기--------------------------------------------------------------------------------------------------
def loadDealprice(bjdong, aptname, area):
    #법정동 코드번호 추출
    temp = bjdong.split()
    temp[1] = temp[1].replace('(', '')
    bjdcode = temp[1].replace(')', '')
    #데이터베이스를 데이터프레임으로 가져오기
    dealDB = AptDeal.query.filter_by(bjdcode=bjdcode, apartment=aptname)
    df = pd.read_sql_query(dealDB.statement, dealDB.session.connection())
    for n in range(len(df)):
        df.loc[n, 'area'] = int(float(df.loc[n, 'area']))#전용면적 소수점이하 버리기
        df.loc[n, 'dealday'] = int(df.loc[n, 'dealday'])
        df.loc[n, 'dealmonth'] = int(df.loc[n, 'dealmonth'])
        df.loc[n, 'dealyear'] = int(df.loc[n, 'dealyear'])
    #찾고자하는 전용면적으로 분리하기
    resultdf = df[df['area'] == int(area)]
    resultdf = resultdf.sort_values(by=['dealyear','dealmonth','dealday'], ascending=False)
    resultdf = resultdf.reset_index(drop=True)#index초기화
    print(resultdf)
    resultList=[]
    buildyear = df.loc[0, 'buildyear']
    for o in range(len(resultdf)):
        resultList.append([o, resultdf.loc[o, 'dealyear'], resultdf.loc[o, 'dealmonth'], resultdf.loc[o, 'dealday'], resultdf.loc[o, 'floor'], resultdf.loc[o, 'price']])
    return buildyear, resultList

#전용면적 체크--------------------------------------------------------------------------------
def checkApartarea(bjdong, aptname):
    #법정동 코드번호 추출
    temp = bjdong.split()
    temp[1] = temp[1].replace('(', '')
    bjdcode = temp[1].replace(')', '')
    #데이터베이스를 데이터프레임으로 가져오기
    dealDB = AptDeal.query.filter_by(bjdcode=bjdcode, apartment=aptname)
    df = pd.read_sql_query(dealDB.statement, dealDB.session.connection())
    df['check'] = 0
    #전용면적 리스트 만들기
    areaList = []#전용면적 목록
    for m in range(len(df)):
        df.loc[m, 'area'] = int(float(df.loc[m, 'area']))#전용면적 소수점이하 버리기
        areaList.append(df.loc[m, 'area'])
    areaList = list(set(areaList))
    areaList.sort()
    return areaList

#아파트이름 체크--------------------------------------------------------------------------------
def checkApartname(keyword, bjdong):
    #법정동 코드번호 추출
    temp = bjdong.split()
    temp[1] = temp[1].replace('(', '')
    bjdcode = temp[1].replace(')', '')
    #데이터베이스를 데이터프레임으로 가져오기
    dealDB = AptDeal.query.filter_by(bjdcode=bjdcode)
    df = pd.read_sql_query(dealDB.statement, dealDB.session.connection())
    df['check'] = 0
    #찾고자하는 아파트명에서 두글자씩 추출해서 아파트리스트와 비교하여 두글자가 포함되면 'check'값을 1 올린다.
    for i in range(len(keyword)-1):
        a1 = keyword[i] + keyword[i+1]
        for j in range(len(df)):
            if a1 in (str(df.loc[j,'bjdong']) + str(df.loc[j,'apartment'])):
                df.loc[j,'check'] += 1
    
    aptList = []#'check'값이 가장 높은 가장높은 아파트를 뽑는다.
    for k in range(len(df)):
        if df.loc[k,'check'] == df['check'].max():
            aptList.append(df.loc[k,'apartment'])
    aptList = list(set(aptList))
    aptList.sort()
    return aptList

#법정동코드 찾기------------------------------------------------------------------------------------------------------------
def checkBjdcode(keyword):
    #데이터베이스를 데이터프레임으로 가져오기
    bjdDB = BjdCode.query.filter()
    df = pd.read_sql_query(bjdDB.statement, bjdDB.session.connection())
    df['check'] = 0
    #찾고자하는 아파트명에서 두글자씩 추출해서 아파트리스트와 비교하여 두글자가 포함되면 'check'값을 1 올린다.
    for i in range(len(keyword)-1):
        a1 = keyword[i] + keyword[i+1]
        for j in range(len(df)):
            if a1 in (str(df.loc[j,'gu']) + str(df.loc[j,'dong']) + str(df.loc[j,'apartment'])):
                df.loc[j,'check'] += 1
    
    bjdList = []
    #check 제일 큰 값이 2보다 작으며 결과없음으로 처리
    if df['check'].max() < 2:
        return bjdList
    #check값이 제일 큰 법정동 코드를 가져온다.
    for j in range(len(df)):
        if df.loc[j,'check'] == df['check'].max():
            bjdList.append(str(df.loc[j,'gu']) + ' ' + ' (' + str(df.loc[j,'bjdcode'])[0:5] + ')')
    bjdList = list(set(bjdList))
    bjdList.sort()
    return bjdList

#관리용 코드

#공공데이터포털 아파트 실거래가 데이터베이스 만들기-------------------------------------------------------
def makepricedb(period):
    import requests
    import xml.etree.ElementTree as ET
    import pandas as pd
    from .. import db

    serviceKey = 'XS%2FfcMwMTBUQfYl8hPGTIjWgVfnZ12m6jvjMJsJQKcBXdgE1pCJc2GgcH9YJsVUYr3pSxsJGS4LVTYN8VqiESA%3D%3D'
    pageNo = '1'
    numOfRows = '9999'

    #중복 데이터베이스 삭제
    trashlist = AptDeal.query.filter((AptDeal.dealyear == int(period[0:4])) & (AptDeal.dealmonth == int(period[4:6])))
    for trash in trashlist:
        print(trash)
        db.session.delete(trash)
        db.session.commit()
        print(period + "데이터...삭제")
          
    aptbjd_list = BjdCode.query.all()
    bjdCodeList = []
    for aptbjd in aptbjd_list:
        bjdCodeList.append(str(aptbjd.bjdcode)[0:5])
    bjdCodeList = list(set(bjdCodeList))
    bjdCodeList.sort()
    

app/templates/apart/apartment.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="padding-top: 80px;">
  <h1 style="border-bottom: 1px solid black;">아파트 실거래가 조회</h1>
</div>

<div class="container" style="padding-top: 20px;">
  <form action="{{ url_for('apartment.search_code') }}">
    <input type="text" name="keyword" id="keyword" placeholder="아파트를 입력하세요" style="height: 40px;">
    <button type="submit" class="btn btn-primary" style="margin-left: 10px; width: 80px; height: 40px;">검 색</button> 
  </form>
</div>

{% endblock %}

app/templates/apart/apartment_DB.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="padding-top: 80px;">
  <h1 style="border-bottom: 1px solid black;">아파트 실거래가 데이터베이스</h1>
</div>

{% if dbcode == 1 %}
  <div class="container" style="padding-top: 20px;">
    실거래가 데이터베이스 만들기 완료
  </div>

{% elif dbcode == 2 %}
  <div class="container" style="padding-top: 20px;">
    법정동코드 데이터베이스 만들기 완료
  </div>

{% elif dbcode == 3 %}
  <div class="container" style="padding-top: 20px;">
    <p>법정동코드 리스트</p>
    <div class="container text-center"></div>
      <div class="row">
        {% for sido in sidoList%}
          <div class="col">
            {{ sido[1] }}<br>
            {% for bjdcode in bjdCodeList %}
              {% if bjdcode[0:2] == sido[0] %}
                {{ bjdcode }}<br>
              {% endif %}
            {% endfor %}
          </div>
        {% endfor %}
      </div>
    </div>
  </div>

{% elif dbcode == 4 %}
<div class="container" style="padding-top: 20px;">
  아파트 이름 수정완료
</div>

{% elif dbcode == 5 %}
<div class="container" style="padding-top: 20px;">
  실거래가 데이터베이스 삭제완료
</div>

{% endif %}

{% endblock %}

app/templates/apart/apartment_search_area.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="padding-top: 80px;">
  <h1 style="border-bottom: 1px solid black;">아파트 실거래가 조회</h1>
</div>

<div class="container">
  <h5>'{{ keyword }}' 검색결과</h5>
</div>

{% if areaList|length == 0 %}
<div class="container" style="padding: 20px;">
  <p>검색결과가 없습니다.</p>
</div>

{% else %}
<div class="container" style="padding: 10px;">
  <form action="{{ url_for('apartment.search_result') }}" method="post">
    <input type="text" name="keyword" id="keyword" value="{{ keyword }}" style="display: none;">
    <select class="form-control input-lg" name="bjdong" id="bjdong" style="display: inline; width: auto">      
      <option value="{{ bjdong }}">{{ bjdong }}</option>
    </select>
    <select class="form-control input-lg" name="aptname" id="aptname" style="display: inline; width: auto">
        <option value="{{ aptname }}">{{ aptname }}</option>
    </select>
    <select class="form-control input-lg" name="area" id="area" style="display: inline; width: auto">
        {% for area in areaList %}      
        <option value="{{ area }}">{{ area }} (m2)</option>
        {% endfor %}
      </select>
    <button type="submit" class="btn btn-primary" style="margin-left: 10px; width: 80px; height: 40px;">확인</button>
  </form>
</div>
{% endif %}

{% endblock %}

app/templates/apart/apartment_search_code.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="padding-top: 80px;">
  <h1 style="border-bottom: 1px solid black;">아파트 실거래가 조회</h1>
</div>

<div class="container">
  <h5>'{{ keyword }}' 검색결과</h5>
</div>

{% if bjdList|length == 0 %}
<div class="container" style="padding: 20px;">
  <p>검색결과가 없습니다.</p>
</div>

{% else %}
<div class="container" style="padding: 10px;">
  <form action="{{ url_for('apartment.search_name') }}" method="post">
    <input type="text" name="keyword" id="keyword" value="{{ keyword }}" style="display: none;">
    <select class="form-control input-lg" name="bjdong" id="bjdong" style="display: inline; width: auto">
      {% for bjdcode in bjdList %}
        <option value="{{ bjdcode }}">{{ bjdcode }}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary" style="margin-left: 10px; width: 80px; height: 40px;">확인</button>
  </form>
</div>
{% endif %}

{% endblock %}

app/templates/apart/apartment_search_name.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="padding-top: 80px;">
  <h1 style="border-bottom: 1px solid black;">아파트 실거래가 조회</h1>
</div>

<div class="container">
  <h5>'{{ keyword }}' 검색결과</h5>
</div>

{% if aptList|length == 0 %}
<div class="container" style="padding: 20px;">
  <p>검색결과가 없습니다.</p>
</div>

{% else %}
<div class="container" style="padding: 10px;">
  <form action="{{ url_for('apartment.search_area') }}" method="post">
    <input type="text" name="keyword" id="keyword" value="{{ keyword }}" style="display: none;">
    <select class="form-control input-lg" name="bjdong" id="bjdong" style="display: inline; width: auto">      
      <option value="{{ bjdong }}">{{ bjdong }}</option>
    </select>
    <select class="form-control input-lg" name="aptname" id="aptname" style="display: inline; width: auto">
      {% for apt in aptList %}
        <option value="{{ apt }}">{{ apt }}</option>
      {% endfor %}
    </select>
    <button type="submit" class="btn btn-primary" style="margin-left: 10px; width: 80px; height: 40px;">확인</button>
  </form>
</div>
{% endif %}

{% endblock %}

app/templates/apart/apartment_search_result.html
{% extends 'base.html' %}
{% block content %}

<div class="container" style="padding-top: 80px;">
    <h1 style="border-bottom: 1px solid black;">아파트 실거래가 조회</h1>
</div>

<div class="container">
<h5>{{ aptname }}({{ buildyear }}) - {{ area }} m<sup>2</sup></h5>
</div>

<div class="table-responsive">
    <table class="table table-hover table-sm">
        <thead>
            <th>거래일</th>
            <th>실거래가(층)</th>
        </thead>
        <tbody class="table-group-divider">
            {% for result in resultList %}
            <tr>
                <td>{{ result[1]}}.{{ result[2] }}.{{ result[3] }}</td>
                <td>{{ result[5]}}원 ({{ result[4]}}층)</td>
            </tr>
            {% endfor %}
        </tbody>

    </table>
</div>

{% endblock %}